"Vim plug
set nocompatible              " required
filetype off                  " required

" --------------------------------
call plug#begin()
" search
Plug '~/.fzf'

" git
Plug 'tpope/vim-fugitive'
Plug 'airblade/vim-gitgutter'
Plug 'zivyangll/git-blame.vim'

if has('nvim')
  " code completetion
  Plug 'neoclide/coc.nvim', {'branch': 'release'}
  " theme
  Plug 'bluz71/vim-nightfly-colors', {'branch': 'legacy'}
  Plug 'NLKNguyen/papercolor-theme'
  Plug 'folke/tokyonight.nvim', { 'branch': 'main' }
  Plug 'Tsuzat/NeoSolarized.nvim', { 'branch': 'master' }
endif

"vim theme
Plug 'dracula/vim', { 'as': 'dracula' }

" Tree
if has("nvim")
  Plug 'nvim-lua/plenary.nvim'
  Plug 'nvim-tree/nvim-web-devicons'
  Plug 'MunifTanjim/nui.nvim'
  Plug 'nvim-neo-tree/neo-tree.nvim', { 'branch': 'v2.x' }
endif

if !has("nvim")
  Plug 'preservim/nerdtree'
  Plug 'baopham/vim-nerdtree-unfocus'
  Plug 'ryanoasis/vim-devicons'
endif
  

call plug#end()
"----------------------------------------------------------
"----------------------------------------------------------

" OPTIONS
syntax on
set tabstop=4
set shiftwidth=4
set expandtab
set ai
set number
set hlsearch
set ruler
set autoindent
set cursorline

set noswapfile
set nobackup
set nofixendofline
set lazyredraw
"set updatetime=100
highlight Comment ctermfg=green
set mouse=a
if !has('nvim')
  set ttymouse=xterm2
endif


" COLOR
if !has('nvim')
  set background=dark
  colorscheme dracula
  hi clear SignColumn
endif


if has('nvim')
  set termguicolors
  set background=dark
  colorscheme dracula
endif


" KEY MAP
nnoremap <C-p> :FZF<CR>
nnoremap <Leader>s :<C-u>call gitblame#echo()<CR>
inoremap jk <ESC>


" CLEVER TAB
function! CleverTab()
  if strpart( getline('.'), 0, col('.')-1 ) =~ '^\s*$'
    return "\<Tab>"
  else
    return "\<C-N>"
  endif
endfunction
inoremap <Tab> <C-R>=CleverTab()<CR>


" GITGUTTER SIGNS
let g:gitgutter_sign_added    = '┃'
let g:gitgutter_sign_modified = '┋'



" TREE CONFIG
if !has('nvim')
  noremap <Leader>n :NERDTreeToggle<CR>
  " Start NERDTree and put the cursor back in the other window.
  " autocmd VimEnter * NERDTree | wincmd p

  " Open the existing NERDTree on each new tab.
  " autocmd BufWinEnter * if getcmdwintype() == '' | silent NERDTreeMirror | endif

  " close nerdtree when close tab
  autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

  " nerdtree to the right
  let g:NERDTreeWinPos = "right"
endif

if has('nvim')
  nnoremap <C-b> :Neotree float reveal<CR>
  nnoremap <Leader>g :Neotree float git_status<CR>
endif

