# Improve colors
# set -g default-terminal 'screen-256color'
set -g default-terminal "xterm-256color"
set -ag terminal-overrides ",xterm-256color:Tc"

# viu image
set -g allow-passthrough on
set -g visual-activity off
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM

# Set scrollback buffer to 10000
set -g history-limit 10000

unbind C-b
set -g prefix '\' 
bind-key '\' last-window
bind-key e send-prefix

set -g status-right-length 50
set -g status-left-length 20
set -g status-justify left
set -g status-position bottom

set -g status-left ''

### COLOR ###
# palette from nvim/helix-nvim/lua/helix/colors.lua
helix_white="#ffffff"
helix_lilac="#dbbfef"
helix_lavender="#a4a0e8"
helix_comet="#5a5977"
helix_bossanova="#452859"
helix_midnight="#3b224c"
helix_revolver="#281733"

helix_silver="#cccccc"
helix_sirocco="#697c81"
helix_mint="#9ff28f"
helix_almond="#eccdba"
helix_chamois="#e8dca0"
helix_honey="#efba5d"

helix_apricot="#f47868"
helix_lightning="#ffcd1c"
helix_delta="#6f44f0"

helix_blue="#61afef"
helix_diff_plus="#35bf86"
helix_diff_minus="#f22c86"
helix_selection="#540099"
helix_matched_bracket="#6c6999"

color_tx_1=$helix_lilac      # bright text
color_tx_2=$helix_lavender   # normal text
color_tx_3=$helix_comet      # dim text
color_bg_1=$helix_midnight   # editor bg
color_bg_2=$helix_revolver   # statusline bg
color_ui_1=$helix_bossanova  # cursorline / inactive ui
color_ui_2=$helix_comet
color_ui_3=$helix_matched_bracket

color_red=$helix_apricot
color_orange=$helix_honey
color_yellow=$helix_lightning
color_green=$helix_mint
color_cyan=$helix_sirocco
color_blue=$helix_blue
color_purple=$helix_delta
color_magenta=$helix_diff_minus

# status
set -g status-position bottom
set -g status "on"
set -g status-bg $color_bg_2
set -g status-fg $color_tx_2
set -g status-justify "left"
set -g status-left-length "100"
set -g status-right-length "100"

# messages
set -g message-style "fg=$color_tx_1,bg=$color_bg_2,align=centre"
set -g message-command-style "fg=$color_tx_1,bg=$color_ui_1,align=centre"

# panes
set -g pane-border-style fg=$color_ui_1
set -g pane-active-border-style fg=$color_tx_1

# windows
setw -g window-status-activity-style fg=$color_yellow,bg=$color_bg_2,none
setw -g window-status-separator ""
setw -g window-status-style fg=$color_tx_3,bg=$color_bg_2,none

# statusline
set -g status-right "#{?client_prefix,#[fg=#$color_bg_2#,bg=#$color_red],#[fg=#$color_bg_2#,bg=#$color_green]}  #S #[fg=#$color_bg_2,bg=#$color_orange] 모#H #[fg=#$color_tx_1,bg=#$color_purple]  %Y-%m-%d %H:%M "

# window-status
setw -g window-status-format "#[bg=#$color_bg_2,fg=#$color_tx_3] #I #W "
setw -g window-status-current-format "#[bg=#$color_bg_1,fg=#$color_tx_1,bold] #I *#W "

# Modes
setw -g clock-mode-colour $color_blue
setw -g mode-style fg=$color_tx_1,bg=$helix_selection,bold

## END COLOR ###



set-option -g allow-rename off # for permanently remame windows
set -g renumber-windows on # renumber windows when a window is closed


bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
